#!/bin/bash
FILE=thingscript/gallery_list

#Assumes gallery items in pics/ and models in output/
ls pics/*.png pics/*.gif pics/*.jpg pics/*.jpeg \
    | while read line; do echo plain $line; done > $FILE
ls output/*.stl output/*.STL \
    | while read line; do echo initially_povray $line; done >> $FILE

ls *.scad \
    | while read line; do echo via_openscad $line initially_povray; done >> $FILE

ls output/*.dxf \
    | while read line; do echo via_assimp $line initially_povray

echo $FILE
