#!/bin/bash
#Generates the default entry for the gallery list.

#TODO optionally postponing figuring out default.(`el/sel/gallery/auto`)

echo $1 > /dev/stderr
case $1 in
    *.png | *.gif | *.jpg | *.jpeg )
        echo plain $1 ;;
    *.stl)
        echo initially_povray $1 ;;
    *.scad)
        echo via_openscad $1 initially_povray ;;
    *.dxf)
        echo via_assimp $1 initially_povray ;;
    *.pdf | *.svg )
        echo via_png $1 plain ;;
    *)
        echo no_default $1 ;;
esac
