#!/bin/bash
#
#  Copyright (C) 30-05-2013 Jasper den Ouden.
#
#  This is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#

#Lays out a list of the images in javascript.
if [ "$2" != "" ]; then #Argument specifies a gallery
    GALLERY_LIST_FILE="$2" #TODO multiple galleries wont actually work.(TODO why not??)
fi
gallery_list()
{
    if [ "$GALLERY_LIST_FILE" != "" ]; then
        cat "$GALLERY_LIST_FILE"
    else
        thingscript cat_get gallery_list
    fi
}

PATH=$PATH:$ROOTLIKE/bin/

echo '<span style="position:absolute" id="pre_viewer"></span>'
echo '<img class="viewer" id="viewer" onclick="use_action_file()">' #Lays out main image.
echo '<span style="position:absolute" id="post_viewer"></span><br>'
echo '<p class="gal_bar">'

#Array of image file names so an index can identify them.
gallery_list | grep -vxP "#.+" | while read el; do
    name=$(echo $el | cut -f1 -d' ')
    #Basically thingscript exec but checks if it exists so it can say it is a gallery subel.
    GOT=$(thingscript get el/sel/gallery/$name)
    if [ "$GOT" == "" ]; then
        echo Couldnt find el/sel/gallery/$name, the subelement of gallery named
        echo $name might not exist.
    fi
    $GOT $(echo $el | cut -f2- -d' ')
done
echo '</p>'
#Initialize and go to the right thing.
echo '<script>main_image="'$(thingscript cat_get main_image)'";'
echo 'gallery_initial();by_url(location.href);</script>'
echo '<script src="tso/gallery_other.js"></script>'
