#!/bin/bash

#Make a js file and it enables immediately when shown.
js_stl=$(want $1-stl2.js)
pov=$(want $1-stl2.pov)

echo '<img onclick="to_img_re_url('\'$js_stl\'')" src="'$(want $pov-thumb_povray.png)'" class="gal">'
