#!/bin/bash

handle_release()
{
    echo '<a href="'$2'">'$1'</a>'
}

RELEASES_FILE=$(thingscript get releases)
if [ "$RELEASES_FILE" != "" ]; then
    echo '<span class="info_name">Releases:</span>'
    cat $RELEASES_FILE | while read line; do handle_release $line; done
fi
