#!/bin/bash
#Places the CSS file link, making the file at thingscript/resource/tso/style.css,
# if needed.

#Use one right on project.
if [ -e thingscript/resource/style.css ]; then
    echo -n thingscript/resource/style.css
    exit 0
fi

url=$(thingscript url style_url)
if [ "$url" == "" ]; then #Copy the default.
    STYLE_FILE=thingscript/resource/tso/style.css
    mkdir -p $(dirname $STYLE_FILE)
    cp $(thingscript get resource/style.css) $STYLE_FILE
    echo -n $STYLE_FILE
else #Use provided url.
    echo -n $url
fi
