#!/bin/bash
#
#  Copyright (C) 22-05-2013 Jasper den Ouden.
#
#  This is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#

#Lays out a list of the images in javascript.
FIRST="true"
for el in `grep -vxP "#.+" $1`; do
    if [ $FIRST == "true" ]; then
        echo '<script>
var imgs = ["'$el\"
        FIRST="false"
    else
        echo ',"'$el'"'
    fi
done
echo '];

var designs =[];'

STL2JS=`thingscript get scripts/bin/stl2js`
for el in `grep -xP '.+\.(stl|obj)' $1 | grep -vxP '#.+'`; do
    #Exists and is up to date.
    file=$PROJECT_DIR$el
    if [ $file.js -nt $file ]; then
        echo skipping: stl2js $file\; already done > /dev/stderr
    else
        echo 'designs["'$el'"]=' > $file.js
        $STL2JS $file >> $file.js
        echo ';' >> $file.js
    fi
    #TODO optional delayed loads? 
done

#Some functions to switch to images.
echo '
var cur_gal_index = 1;
function to_img_re_url(index)
{   var to_ind = location.href.indexOf("#");
    if( to_ind != -1 )
    {   location.href = location.href.substr(0,to_ind) + "#img_" + index; }
    else
    {   location.href = location.href + "#img_" + index; }
    to_img(index)
}

function to_img(index)
{   cur_gal_index = index;
    var file = imgs[index];
    var ext  = file.substr(file.length-4);
    if( ext==".jpg" || ext==".png" || ext==".gif" ) //Put an image there.
    {   document.getElementById("viewer").src = file;
    }
    else if( ext==".stl" || ext==".obj" ) //Disable image, put design.
    {    js_import(file + ".js");
         thingiview.loadArray(designs[file]);
         document.getElementById("viewer").src = null;
    }
}
</script>'

#Lays out the main image and...
FIRST=`head -n 1 $1`
echo '<img id="viewer" style="width:400px;height:400px">'
I=0
echo '<table><tr>'
for el in `grep -vxP '#.+' $1`; do
    img=$el
    file=$PROJECT_DIR$el
    echo $img | grep .stl > /dev/null
    if [ "$?" == "0" ]; then #Make image for .stl
        if [ $file.png -nt $file ]; then #Check if up to date.
            echo skipping: stl2png $file\; already done > /dev/stderr
        else
            echo running: stl2png $img > /dev/stderr
            `thingscript get scripts/bin/stl2png` $file 80 80 >> /dev/null
        fi
        img=$img.png #(always convert to the image)
    fi
    echo '<td><img onclick="to_img_re_url('$I')" src="'$img'"></td>'
    I=`expr $I + 1`
done
# ...a set of images with which to navigate.
echo '</tr></table>
<script>
var any_p =0;
for (var i=0 ; i<imgs.length ; i++)
{   if( location.href.indexOf("#img_"+i)!= -1 )
    {   to_img(i);
        any_p=1;
        break;
    }
}
if( any_p==0 ){ to_img(0); }
</script>'
