#!/bin/bash

file=$1
ofile=`thingscript ibin tso $file yes`

thingscript ibin memoize $file $ofile.data get_stl_info with_stdout | \
             memoize $file $ofile.pov stl2pov no_stdout > /dev/stderr

echo $ofile.pov