#!/bin/bash

#Way to add links without having to waste words why.
echo '<h2>Related</h2>'
echo "$@" | tr ' ' '\n' | tr '\t' '\n' | tail -n+2 | while read line; do
     if [ "$line" != "" ]; then
          $(thingscript get el/a) '' $line
          echo '<br>'
     fi
done
