#!/bin/bash
#Make a js file and it enables immediately when shown.
memoize $1 $1.js "`thingscript get scripts/stl2js` $link" no_stdout > /dev/stderr;

echo '<img onclick="to_img_re_url('\'$1.js\'')" src="'`figure_image $1`'" class="gal">'
