#!/bin/bash
#First use openscad to convert to .stl, then do the other thing.
#Example entries: `via_openscad some.scad initially_povray`
#                 `via_openscad some.scad just_povray`
#                 `via_openscad some.scad stl2js`

#echo === > /dev/stderr
#thingscript get script/openscad > /dev/stderr
#echo > /dev/stderr
#thingscript get el/sel/gallery/$2 > /dev/stderr

stl=$(thingscript exec scripts/openscad $1)
thingscript exec el/sel/gallery/$2 $stl # $(echo "$@" | cut -f 3- -d' ')
