#!/bin/bash

if [ "$2" != "" ]; then
    echo gallery from arg $2 > /dev/stderr
    `thingscript get scripts/gallery` $2
fi

GALLERY_LIST_FILE=`thingscript get gallery_list` #TODO stream it instead?
if [ "$GALLERY_LIST_FILE" == "" ]; then #Doesnt exist yet.
    ls $PROJECT_NAME/pics | grep -P '(png|gif|jpg|jpeg)'\
       | while read line; do echo pics/$line; done > $PROJECT_DIR/page/gallery_list 
    GALLERY_LIST_FILE=$PROJECT_DIR/page/gallery_list
fi
`thingscript get scripts/gallery` $GALLERY_LIST_FILE
