#!/bin/bash
#'Binary' files from the sources

cat_or_run() #List 
{
    if [ "$1" == "" ]; then
        $2
    else
        cat $1
    fi
}

RUN='ls $PROJECT_DIR/output/* $PROJECT_DIR/*.stl
 $PROJECT_DIR/*.obj $PROJECT_DIR/*.dxf $PROJECT_DIR/*.svg'
cat_or_run `get output_list` $RUN | while read line; do
    echo '<a href="'$PROJECT_DIR/$line'">$line</a><br>'
done
