#!/bin/bash

#TODO stuff

cat_or_run() #List 
{
    if [ "$1" == "" ]; then
        $2
    else
        cat $1
    fi
}

RUN='ls $PROJECT_DIR/src/* $PROJECT_DIR/*.blender
 $PROJECT_DIR/*.skp $PROJECT_DIR/*.scad $PROJECT_DIR/*.escad'
cat_or_run `get output_list` $RUN | while read line; do
    echo '<a href="'$PROJECT_DIR/$line'">$line</a><br>'
done ;;
