#!/bin/bash

LINK=`thingscript get author_link`
if [ "$LINK" != "" ]; then
    echo '<a href='`cat $LINK`'>'`thingscript cat_get author`'</a>'
else
    thingscript cat_get author
fi
#Run the script to output the image drawing html.
AUTHOR_IMG_SCRIPT=`thingscript get el/author_img` 
if [ "$AUTHOR_IMG_SCRIPT" != "" ]; then
    $AUTHOR_IMG_SCRIPT
fi
