#!/bin/bash

handle_release()
{
    echo '<a href="'$2'">'$1'</a>'
}

RELEASES_FILE=$(thingscript get releases)
if [ "$RELEASES_FILE" != "" ]; then
    echo Can be found on:
    cat $RELEASES_FILE | while line=read; do handle_release $line; done
fi
