#!/bin/bash

#TODO stuff

cat_or_run() #List 
{
    if [ "$1" == "" ]; then
        $2
    else
        cat $1
    fi
}

RUN='ls src/* *.blender *.skp *.scad *.escad'
cat_or_run `get output_list` $RUN | while read line; do
    echo '<a href="'$line'">$line</a><br>'
done ;;
