#!/bin/bash

#TODO this looks like something that should be the same everywhere too.
#(name -> where with suggested website root dir)

if [ -e thingscript/etc/style.css ]; then
   STYLE_FILE=thingscript/etc/style.css
else
   ROOTLIKE=`thingscript cat_get rootdir`;
   STYLE_FILE=""
   WHERE=main/etc/style.css
   if [ -e ~/.thingscript/$WHERE ]; then
       FROM=~/.thingscript/$WHERE
       STYLE_FILE=$ROOTLIKE'etc/style.css'
   else
       if [ -e /usr/etc/thingscript/$WHERE ]; then
           FROM=/usr/etc/thingscript/$WHERE
           STYLE_FILE=$ROOTLIKE'etc/etc/style.css'
       else 
           if [ -e /usr/share/thingscript/$WHERE ]; then
               FROM=/usr/share/thingscript/$WHERE
               STYLE_FILE=$ROOTLIKE'share/etc/style.css'
           fi
       fi
   fi
   mkdir -p `dirname STYLE_FILE` > /dev/null
   cp -uv $FROM $STYLE_FILE > /dev/stderr #Put into place.
fi

echo '<link rel="stylesheet" type="text/css" href="'$STYLE_FILE'">'
