#!/bin/bash

TAGSFILE=`thingscript get tags`
if [ "$TAGSFILE" != "" ]; then
    COMMA='';
    case "$2" in
        html)
            echo '<span class="info_name">tags:</span>'
            grep -vxP '#.+' $TAGSFILE | while read line; do
                echo $COMMA '<span class="tag">'$line'</span>'
                COMMA=',';
            done | tr -d '\n';;
        plain)
            grep -vxP '#.+' $TAGSFILE | while read line; do
                echo $COMMA$line
                COMMA=',';
            done | tr -d '\n';;
        html_head)
            command=`thingscript get el/tags`
            echo '<meta name=keywords, content="'`$command dud plain`'">' |tr -d '\n';;
        *)
            echo E: What way do you want the tags? dont have \"$2\" > /dev/stderr;;
    esac
fi
