#!/bin/bash
FILE=thingscript/gallery_list

#Figure these are the gallery items.
ls pics | grep -P '(png|gif|jpg|jpeg)'\
       | while read line; do echo pics/$line; done > $FILE
ls output/ | grep -P 'stl'\
       | while read line; do echo output/$line; done >> $FILE

echo $FILE
