#!/bin/bash

#Look up/create gallery list, and assume the first is the proper thumbnail.
grep -vxP "#.+" `thingscript get gallery_list` | grep -vP '.+\.stl' | head -n 1 > thingscript/thumbnail

echo thingscript/thumbnail
