#!/bin/bash

#Look up/create main image
TN=$(thingscript get main_image)
#Make up a thumbnail from it.
THUMB=$(thingscript exec scripts/thumb $TN)

echo $THUMB > thingscript/thumbnail
echo thingscript/thumbnail
