#!/bin/bash
#Uses openscad or extopenscad(implicitcad) 
#to convert to image/stl(previous is default)

ext=stl
if [ "$2" != "" ]; then #figure extension.
   ext=$2
fi
ofile=$(tso $1).$ext

prog=openscad
case $1 in
    *.scad)
        prog=openscad ;;
    *.escad)
        prog=extopenscad ;;
esac

if_newer $1 $ofile "$prog $1 -o $ofile"
echo $ofile
